import { BUSINESS as B, SIZES, PRICES, EXTRAS, money, esc } from './site-core.js';

const paths = {
  arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
  diagonal: '<path d="M6 18 18 6M6 6h12v12"/>',
  paw: '<ellipse cx="7" cy="7" rx="2" ry="3"/><ellipse cx="17" cy="7" rx="2" ry="3"/><ellipse cx="3" cy="12" rx="1.6" ry="2.4"/><ellipse cx="21" cy="12" rx="1.6" ry="2.4"/><path d="M6 18c0-3 4-7 6-7s6 4 6 7c0 4-4 2-6 2s-6 2-6-2Z"/>',
  scissors: '<circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="m8 8 12 12M8 16 20 4m-8 8 3-3"/>',
  wash: '<path d="M3 12h18v3a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5v-3Zm2 8v2m14-2v2M6 12V5a3 3 0 0 1 6 0"/><path d="M10 6h4M16 8h.01M19 5h.01"/>',
  home: '<path d="m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8"/>',
  heart: '<path d="M20 5c-3-3-6-1-8 1-2-2-5-4-8-1-5 5 2 11 8 15 6-4 13-10 8-15Z"/>',
  clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  pin: '<path d="M19 10c0 6-7 12-7 12S5 16 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  text: '<path d="M3 4h18v13H9l-6 4V4Z"/><path d="M7 8h10M7 12h7"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
  mail: '<rect x="3" y="5" width="18" height="14"/><path d="m3 6 9 7 9-7"/>'
};
export const icon = (name, className = '') => `<svg class="icon ${className}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.paw}</svg>`;
const link = (label, url, style = 'primary') => `<a class="button ${style}" href="${url}">${label}${icon('arrow')}</a>`;
const eyebrow = text => `<p class="eyebrow">${text}</p>`;
const intro = (label, title, description) => `<section class="page-intro container">${eyebrow(label)}<h1>${title}</h1><p class="lead">${description}</p></section>`;
const image = (src, alt, cls = '', eager = false) => `<img class="${cls}" src="/assets/${src}" alt="${alt}" width="1200" height="1200" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
const checkList = items => `<ul class="check-list">${items.map(item => `<li>${icon('check')}<span>${item}</span></li>`).join('')}</ul>`;

export function header(route) {
  const nav = (label, path) => `<a href="${path}" ${route === path ? 'aria-current="page"' : ''}>${label}</a>`;
  return `<a class="skip-link" href="#main">Skip to content</a>
    <div class="utility-bar"><div class="container"><span>Small local business. Big love for dogs.</span><a href="sms:${B.sms}">${icon('text')}Text us <span>${B.phone}</span></a></div></div>
    <header class="site-header"><div class="container header-inner">
      <a class="brand" href="/" aria-label="Barking Mad Barbers home"><img src="/assets/brand-mark.webp" width="120" height="77" alt=""><span>Barking Mad <b>Barbers</b><small>DOG GROOMING & BOARDING · TAWA</small></span></a>
      <nav class="desktop-nav" aria-label="Main navigation">${nav('Services & prices', '/services/')}${nav('Boarding', '/boarding/')}<details class="nav-details"><summary ${['/team/', '/sanctuary/', '/our-family/', '/helper/'].includes(route) ? 'class="current"' : ''}>About us <span aria-hidden="true">⌄</span></summary><div class="nav-popover">${nav('Meet the team', '/team/')}${nav('Our calm sanctuary', '/sanctuary/')}${nav('Our family', '/our-family/')}${nav('Dog care questions', '/helper/')}</div></details>${nav('Contact', '/contact/')}</nav>
      <div class="header-actions">${link('Book a visit', '/book/')}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav"><span class="menu-lines" aria-hidden="true"></span><span class="sr-only">Menu</span></button></div>
    </div><nav id="mobile-nav" class="mobile-nav container" aria-label="Mobile navigation" hidden>${nav('Services & prices', '/services/')}${nav('Dog boarding', '/boarding/')}${nav('Meet the team', '/team/')}${nav('Our calm sanctuary', '/sanctuary/')}${nav('Our family', '/our-family/')}${nav('Dog care questions', '/helper/')}${nav('Contact & visit', '/contact/')}${link('Book a visit', '/book/')}</nav></header>`;
}
export function footer() {
  return `<footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><a href="/">Barking Mad<br><em>Barbers.</em></a><p>Fresh grooms. Homely stays.<br>A whole lot of love.</p><span class="footer-mark">${icon('paw')} Tawa, Wellington</span></div>
    <div><h2>Come say hello</h2><p>5A Tawa Street<br>Tawa, Wellington</p><p>${B.hours}<br>By appointment only</p><a class="text-link" href="/contact/">Plan your visit ${icon('arrow')}</a></div>
    <div><h2>Let’s talk dogs</h2><a class="footer-phone" href="sms:${B.sms}">${B.phone}</a><p>Texting is best. We may have<br>our hands full with a dog.</p><a class="footer-email" href="mailto:${B.email}">${B.email}</a></div>
    <div><h2>Around here</h2><a href="/services/">Services & prices</a><a href="/boarding/">Dog boarding</a><a href="/helper/">Questions & answers</a><a href="/sign-in/">Saved details</a><h2 class="footer-other">Other sites you might like</h2><a href="https://step-by-stepper.com" target="_blank" rel="noopener noreferrer">Step-by-stepper ${icon('diagonal')}</a><a href="https://scuffingmaddancers.nz" target="_blank" rel="noopener noreferrer">Scuffing Mad Dancers ${icon('diagonal')}</a></div></div>
    <div class="container footer-bottom"><span>© ${new Date().getUTCFullYear()} Barking Mad Barbers</span><span>Groomed with love. Treated like family.</span><a href="#top">Back to top ↑</a></div></footer>`;
}
function cta() {
  return `<section class="booking-banner"><div class="container">${icon('paw', 'banner-paw')}<div>${eyebrow('A good day starts with a happy dog')}<h2>Ready for a little <em>pampering?</em></h2><p>Tell us about your dog. We’ll take it from there.</p></div>${link('Let’s book a visit', '/book/', 'light')}</div></section>`;
}
function servicesCards(withSize = false) {
  return `<div class="service-grid">
    <article class="service-card"><div class="card-top">${icon('scissors')}<span>01 / THE FULL WORKS</span></div><h3>Full Groom</h3><p>A fresh start, from nose to tail. The full tidy-up for a coat that looks and feels good.</p><p class="service-price"><span ${withSize ? 'data-price="Full Groom"' : ''}>${withSize ? '$90' : '$80'}</span><small>${withSize ? 'Small dog · NZD' : 'from · NZD'}</small></p>${checkList(['Bath, blow dry & brush out', 'Full body clip, face & feet finish', 'Nail trim, ear clean & gland expression'])}${link('Choose a full groom', '/book/?service=full', 'outline')}</article>
    <article class="service-card"><div class="card-top">${icon('wash')}<span>02 / FRESHEN UP</span></div><h3>Wash & Dry</h3><p>For muddy adventures and in-between grooms. Clean, fluffy and ready for cuddles.</p><p class="service-price"><span ${withSize ? 'data-price="Wash & Dry"' : ''}>${withSize ? '$50' : '$45'}</span><small>${withSize ? 'Small dog · NZD' : 'from · NZD'}</small></p>${checkList(['Bath, blow dry & brush out', 'Nail trim & gland expression', 'A finishing touch of cologne'])}${link('Choose a wash & dry', '/book/?service=wash', 'outline')}</article>
    <article class="service-card boarding-card"><div class="card-top">${icon('home')}<span>03 / MAKE YOURSELF AT HOME</span></div><h3>Dog Boarding</h3><p>A comfortable place to stay, familiar routines and people who love having dogs around.</p><p class="service-price arrangement">A homely stay<small>Price by arrangement</small></p>${checkList(['Personal care & company', 'Your dog’s familiar routine', 'A meet & greet to get acquainted'])}${link('Explore boarding', '/boarding/', 'outline')}</article>
  </div>`;
}
const FAQS = [
  ['How do I book?', 'Use our booking form to choose a service and prepare a text. You’ll send it from your own messaging app to 027 247 2493. We’ll reply to confirm availability and the final price. An enquiry is not a confirmed appointment.'],
  ['What if my dog is nervous?', 'Let us know when you enquire. Our appointment-only space gives us room to work patiently around your dog’s comfort and confidence. Tell us about anything that helps them settle.'],
  ['How much will my groom cost?', 'Full grooms start at $80 and wash & dry starts at $45. Your estimate depends on your dog’s size and services. Breed, coat condition and matting can affect the final price, which we’ll confirm with you.'],
  ['Can I book more than one dog?', 'Yes. Choose grooming in the booking form, then select “Add another dog”. You can choose separate sizes, services and preferred times, and see an estimate for each dog.'],
  ['What should I bring for boarding?', 'Bring your dog’s own food and harness. Include feeding times, medication, sleep habits and temperament in your enquiry so we can discuss their routine and arrange a meet & greet.'],
  ['Do you take walk-ins?', 'Visits are by appointment only. Our hours are Monday to Saturday, 8:30am–3:00pm. Send a text before coming in so we can arrange a time.']
];
function faqs(all = false) {
  return `<div class="faq-list">${FAQS.slice(0, all ? FAQS.length : 4).map(([q, a], i) => `<details><summary><span><small>0${i + 1}</small>${q}</span>${icon('plus')}</summary><p>${a}</p></details>`).join('')}</div>`;
}
function home() {
  return `<section class="hero container"><div class="hero-copy">${eyebrow('DOG GROOMING & BOARDING IN TAWA')}<h1>Good looks.<br>Great care.<br><em>Happy dogs.</em></h1><p class="lead">From a fresh trim to a cosy stay, we’re here to make your dog feel right at home.</p><div class="actions">${link('Book a visit', '/book/')}${link('Explore our services', '/services/', 'outline')}</div><div class="hero-note">${icon('heart')}<p>Groomed with love.<br><strong>Treated like family.</strong></p></div></div>
    <div class="hero-visual original-artwork"><img class="original-poster" src="/assets/hero-advert.png" width="1024" height="1535" alt="Barking Mad Barbers grooming advert with full grooms from $80 and wash and dry from $45" fetchpriority="high"></div></section>
    <div class="care-strip"><div class="container"><span>${icon('heart')}Patient, personal care</span><span>${icon('scissors')}Tiny to extra large</span><span>${icon('clock')}By appointment</span><span>${icon('pin')}Local to Tawa</span></div></div>
    <section class="section container"><div class="section-heading"><div>${eyebrow('A LITTLE SOMETHING FOR EVERY DOG')}<h2>Looking good.<br><em>Feeling even better.</em></h2></div><p>A proper groom, a quick freshen-up or a home away from home. Find the care that fits your dog.</p></div>${servicesCards()}<p class="fine-print">All prices are in NZD. Final grooming prices depend on breed and coat condition.</p></section>
    <section class="story-section"><div class="container story-grid"><div class="story-photo">${image('team-dog.webp', 'A member of the Barking Mad family relaxing with a dog')}<span class="photo-tab">A FAMILY WITH DOGS AT HEART</span></div><div class="story-copy">${eyebrow('MORE THAN A FRESH HAIRCUT')}<h2>Good with coats.<br><em>Better with dogs.</em></h2><p class="lead">They’re family to you.<br>That’s how we treat them, too.</p><p>We’re a local Tawa business with a soft spot for dogs and a patient approach to their care. We make time to get to know your dog, their routine and the little things that help them feel comfortable.</p><div class="value-row">${icon('heart')}<div><h3>Care at their pace</h3><p>A calm space and one-on-one attention.</p></div></div><div class="value-row">${icon('home')}<div><h3>A familiar face, a friendly place</h3><p>Personal care, from hello to home time.</p></div></div><a class="text-link" href="/team/">Get to know us ${icon('arrow')}</a></div></div></section>
    <section class="section container faq-section"><div>${eyebrow('BEFORE THE WAGGING BEGINS')}<h2>A few good<br><em>questions.</em></h2><p>Something else on your mind?<br>We’re only a text away.</p><a class="text-link" href="sms:${B.sms}">Ask us a question ${icon('arrow')}</a></div>${faqs()}</section>${cta()}`;
}
function services() {
  return `${intro('THE MENU', 'Good care. <em>Clear prices.</em>', 'Find the right fit for your dog, from a little freshen-up to the full works.')}<section class="container section-topless"><div class="size-selector"><div><h2>How big is your best friend?</h2><p>Choose a size to compare grooming prices.</p></div><fieldset class="size-options"><legend class="sr-only">Dog size for price comparison</legend>${SIZES.map(size => `<label><input type="radio" name="price-size" value="${size}" ${size === 'Small' ? 'checked' : ''}><span>${size}</span></label>`).join('')}</fieldset></div><div id="service-prices" aria-live="polite">${servicesCards(true)}</div><p class="fine-print">Prices are in NZD. Breed, coat condition and matting may affect the final price. Unsure of your dog’s size? Text us their breed and we’ll help.</p><details class="price-table-details"><summary>See the complete size & price guide ${icon('plus')}</summary>${priceTable()}</details></section>
    <section class="extras-section"><div class="container section"><div class="section-heading"><div>${eyebrow('THE LITTLE EXTRAS')}<h2>Finishing <em>touches.</em></h2></div><p>Book these on their own or add them to a groom. We won’t charge twice for anything already included.</p></div><div class="extras-grid">${Object.entries(EXTRAS).map(([name, amount]) => `<a class="extra-item" href="/book/?extra=${encodeURIComponent(name)}"><span>${name}</span><strong>${money(amount)}</strong>${icon('diagonal')}</a>`).join('')}</div><p class="fine-print">Nail trim and anal gland expression are included with both grooms. Face tidy is also included with a Full Groom.</p></div></section>${cta()}`;
}
export function priceTable() { return `<div class="table-scroll"><table><caption>Grooming base prices · NZD</caption><thead><tr><th scope="col">Dog size</th><th scope="col">Full Groom</th><th scope="col">Wash & Dry</th></tr></thead><tbody>${SIZES.map((size, i) => `<tr><th scope="row">${size}</th><td>${money(PRICES['Full Groom'][i])}</td><td>${money(PRICES['Wash & Dry'][i])}</td></tr>`).join('')}</tbody></table></div>`; }
function boarding() {
  return `${intro('THEIR HOME AWAY FROM HOME', 'Away for a bit?<br><em>They’re in good company.</em>', 'Homely boarding with familiar routines, personal attention and a warm welcome.')}<section class="container split-feature section-topless"><div class="feature-image">${image('team-dog.webp', 'A relaxed dog spending time with the Barking Mad family', '', true)}</div><div class="feature-copy">${eyebrow('STAY A LITTLE WHILE')}<h2>Make themselves<br><em>right at home.</em></h2><p>Good care starts with getting to know your dog. Tell us about their meals, medication, sleep habits and little quirks, so we can talk through the stay together.</p>${checkList(['A meet & greet to get acquainted', 'Familiar feeding and rest routines', 'Company, attention and patient care'])}<div class="notice"><strong>Boarding prices are by arrangement.</strong><p>Send us your dates and your dog’s details. We’ll confirm availability, care needs and cost.</p></div>${link('Enquire about a stay', '/book/?service=boarding')}</div></section><section class="container section"><div class="section-heading"><div>${eyebrow('PACK THE FAMILIAR THINGS')}<h2>A little preparation.<br><em>A more settled stay.</em></h2></div></div><div class="three-up"><article class="info-card">${icon('wash')}<h3>Their own food</h3><p>Bring their usual food and let us know the amounts and feeding times.</p></article><article class="info-card">${icon('paw')}<h3>Their harness</h3><p>Bring a harness that fits comfortably, ready for their stay.</p></article><article class="info-card">${icon('text')}<h3>The little details</h3><p>Tell us about medication, temperament and anything that helps them settle.</p></article></div></section>${cta()}`;
}
function sanctuary() {
  return `${intro('CALM COMES FIRST', 'A gentler pace.<br><em>A happier dog.</em>', 'An appointment-only space where patience, comfort and kindness come first.')}<section class="container split-feature section-topless"><div class="feature-image original-artwork"><img class="original-poster" src="/assets/hero-advert.png" width="1024" height="1535" alt="Barking Mad Barbers dog grooming advert" fetchpriority="high" decoding="async"></div><div class="feature-copy"><h2>A little time makes<br><em>a big difference.</em></h2><p>Every dog is different. We work around their comfort, confidence and coat condition, giving them one-on-one attention in a calm space.</p>${checkList(['Patient care, with room to settle', 'A clean space and gentle grooming products', 'A finish that suits your dog'])}<div class="notice"><strong>A nervous dog? Let’s talk.</strong><p>Tell us about previous experiences or things that worry them when you enquire. We can discuss what might help.</p></div>${link('Tell us about your dog', '/book/')}</div></section>${cta()}`;
}
function team() {
  return `${intro('HELLO FROM TAWA', 'Dog people.<br><em>Through and through.</em>', 'The local family behind the fresh grooms, warm welcomes and cosy stays.')}<section class="container section-topless"><div class="team-grid"><article>${image('team-dog.webp', 'A Barking Mad family member with a dog on his shoulder', '', true)}<div class="team-caption">${eyebrow('DOG-LOVING CARE')}<h2>Always room<br><em>for one more cuddle.</em></h2><p>Friendly, patient care and a finish that suits your dog. We love getting to know the personality underneath all that fur.</p></div></article><article>${image('team-beach.webp', 'A member of the Barking Mad family enjoying a Wellington beach')}<div class="team-caption">${eyebrow('LOCAL ROOTS')}<h2>Your neighbours.<br><em>Your dog’s people.</em></h2><p>A Tawa grooming and boarding business with a personal feel. Find us at 5A Tawa Street, by appointment.</p></div></article></div></section>${cta()}`;
}
const field = (name, label, options = {}) => {
  const { type = 'text', required = false, placeholder = '', autocomplete = '', value = '', id = name, rows } = options;
  const common = `id="${id}" name="${name}" ${required ? 'required' : ''} ${autocomplete ? `autocomplete="${autocomplete}"` : ''} ${placeholder ? `placeholder="${esc(placeholder)}"` : ''}`;
  return `<div class="field"><label for="${id}">${label}${required ? ' <span aria-hidden="true">*</span>' : ''}</label>${rows ? `<textarea ${common} rows="${rows}">${esc(value)}</textarea>` : `<input ${common} type="${type}" value="${esc(value)}" ${type === 'tel' ? 'inputmode="tel"' : ''}>`}</div>`;
};
const sizeSelect = (name, id) => `<div class="field"><label for="${id}">Size <span aria-hidden="true">*</span></label><select id="${id}" name="${name}" required><option value="">Choose a size</option>${SIZES.map(s => `<option>${s}</option>`).join('')}</select></div>`;
export function dogCard(id = 1) {
  return `<fieldset class="dog-card" data-dog="${id}"><legend>Dog <span data-dog-number>${id}</span></legend><div class="dog-card-title">${icon('paw')}<strong data-dog-heading>Dog ${id}</strong><button type="button" class="remove-dog" ${id === 1 ? 'hidden' : ''}>Remove<span class="sr-only"> dog ${id}</span></button></div><div class="form-grid">${field('dog_name', 'Dog’s name', {required:true, id:`dog-${id}-name`, placeholder:'e.g. Charlie'})}${sizeSelect('dog_size',`dog-${id}-size`)}${field('breed','Breed', {required:true,id:`dog-${id}-breed`,placeholder:'e.g. Cavoodle'})}${field('dog_preferred_time','Time for this dog (optional)', {id:`dog-${id}-time`,placeholder:'Use my preferred time'})}</div><fieldset class="service-options"><legend>Choose a groom and/or extras <span aria-hidden="true">*</span></legend><div class="service-checks">${[...Object.keys(PRICES), ...Object.keys(EXTRAS)].map(service => `<label><input type="checkbox" name="services" value="${service}"><span>${service}<small data-option-price>${PRICES[service] ? `from ${money(PRICES[service][0])}` : money(EXTRAS[service])}</small></span></label>`).join('')}</div></fieldset><p class="field-error" data-services-error hidden>Choose at least one service for this dog.</p><p class="dog-subtotal">Choose a size and service to see an estimate.</p></fieldset>`;
}
function book() {
  return `${intro('A LITTLE CARE STARTS HERE', 'Let’s plan their <em>next visit.</em>', 'Choose their care, tell us a little about them, and we’ll get your enquiry ready to text.')}<div class="container booking-layout section-topless"><div><ol class="booking-progress" aria-label="Enquiry progress"><li data-step-indicator="1" aria-current="step"><span>1</span> Their care</li><li data-step-indicator="2"><span>2</span> The details</li><li data-step-indicator="3"><span>3</span> Review & text</li></ol><form id="booking-form" class="booking-form" novalidate><section data-step="1"><p class="eyebrow">STEP 01 / THEIR CARE</p><h2 tabindex="-1">What brings them in?</h2><p>Choose a fresh groom or a homely stay.</p><fieldset class="care-options"><legend class="sr-only">Type of care</legend><label><input type="radio" name="service_type" value="Grooming" checked><span>${icon('scissors')}<strong>Grooming</strong><small>A full groom, freshen-up or extras</small></span></label><label><input type="radio" name="service_type" value="Dog Boarding"><span>${icon('home')}<strong>Dog boarding</strong><small>A cosy stay while you’re away</small></span></label></fieldset><div class="form-navigation"><span class="subtle">No account needed.</span><button type="button" class="button primary" data-next>Next: the details ${icon('arrow')}</button></div></section>
    <section data-step="2" hidden><p class="eyebrow">STEP 02 / THE DETAILS</p><h2 tabindex="-1">Tell us about your dog.</h2><p>Required fields are marked with an asterisk.</p><div class="form-grid">${field('owner_name','Your name',{required:true,autocomplete:'name'})}${field('phone','Phone number',{type:'tel',required:true,autocomplete:'tel',placeholder:'e.g. 027 123 4567'})}${field('email','Email (optional)',{type:'email',autocomplete:'email'})}</div><label class="check-label remember-details"><input type="checkbox" name="remember_details"><span>Save my contact details on this device for next time.</span></label>
    <div id="grooming-fields"><div class="form-grid">${field('preferred_date','Preferred date (optional)',{type:'date'})}${field('preferred_time','Preferred time (optional)',{placeholder:'Morning, afternoon or flexible'})}</div><div id="dogs-list">${dogCard()}</div><button class="add-dog" type="button">${icon('plus')}Add another dog</button>${field('notes','Anything else? (optional)',{rows:3,placeholder:'Coat condition, nerves, special requests…'})}</div>
    <div id="boarding-fields" hidden><div class="form-grid">${field('boarding_dog_name','Dog’s name',{required:true})}${field('boarding_breed','Breed',{required:true})}${sizeSelect('boarding_size','boarding_size')}${field('meet_greet','Meet & greet availability (optional)',{placeholder:'When would suit you?'})}${field('drop_off','Drop-off date',{type:'date',required:true})}${field('pick_up','Pick-up date',{type:'date',required:true})}</div>${field('boarding_notes','Care notes (optional)',{rows:4,placeholder:'Feeding, medication, sleep habits and temperament…'})}<p class="notice">Please bring your dog’s own food and harness for their stay.</p></div><p id="booking-error" class="field-error" role="alert" hidden></p><div class="form-navigation"><button class="button text-button" type="button" data-back>← Back</button><button class="button primary" type="button" data-next>Review enquiry ${icon('arrow')}</button></div></section>
    <section data-step="3" hidden><p class="eyebrow">STEP 03 / REVIEW & TEXT</p><h2 tabindex="-1">Looking good?</h2><p>Here’s the message you’ll send to ${B.phone}. Take a moment to check the details.</p><label for="booking-preview" class="sr-only">Your booking enquiry message</label><textarea id="booking-preview" class="message-preview" readonly rows="14"></textarea><div class="notice"><strong>Your appointment isn’t booked yet.</strong><p>Send the text from your messaging app. We’ll reply to confirm availability and the final price.</p></div><div class="form-navigation"><button type="button" class="button text-button" data-back>← Edit details</button><button type="submit" class="button primary">${icon('text')}Open text message</button></div><button type="button" class="text-link copy-booking">Copy enquiry instead ${icon('arrow')}</button><div id="booking-status" role="status"></div></section></form></div>
    <aside class="booking-aside"><div class="estimate-card"><p class="eyebrow">A LITTLE CLARITY</p><h2>Your estimate</h2><div id="booking-estimate" aria-live="polite" aria-atomic="true"><p>Choose your dog’s size and services to see your estimate here.</p></div><p class="fine-print">Prices are NZD. Final grooming prices depend on breed and coat condition.</p></div><div class="aside-note">${icon('text')}<div><h3>Prefer a quick text?</h3><p>That works, too.</p><a class="text-link" href="sms:${B.sms}">${B.phone} ${icon('arrow')}</a></div></div><details class="aside-guide"><summary>Full grooming price guide ${icon('plus')}</summary>${priceTable()}</details></aside></div>`;
}
function contact() {
  return `${intro('SAY HELLO', 'We’re only a <em>text away.</em>', 'Ask a question, plan a visit or tell us what your dog needs. Texting is the easiest way to reach us.')}<section class="container contact-layout section-topless"><div class="contact-details"><a class="contact-number" href="sms:${B.sms}">${B.phone}${icon('diagonal')}</a><p>We may be with a dog. Leave us a text and we’ll get back to you when we’re free.</p><div class="contact-detail">${icon('pin')}<div><h2>Find us in Tawa</h2><p>5A Tawa Street<br>Tawa, Wellington</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=5A%20Tawa%20Street%2C%20Tawa%2C%20Wellington" target="_blank" rel="noopener noreferrer">Get directions ${icon('diagonal')}</a></div></div><div class="contact-detail">${icon('clock')}<div><h2>Come by appointment</h2><p>${B.hours}<br>Bookings only — no walk-ins.</p></div></div><div class="contact-detail">${icon('mail')}<div><h2>Prefer email?</h2><a class="break-link" href="mailto:${B.email}">${B.email}</a></div></div></div><form class="form-panel" id="contact-form"><p class="eyebrow">LET’S TALK DOGS</p><h2>Write us a little note.</h2><div class="form-grid">${field('name','Your name',{required:true,autocomplete:'name'})}${field('phone','Phone (optional)',{type:'tel',autocomplete:'tel'})}</div>${field('email','Email (optional)',{type:'email',autocomplete:'email'})}${field('message','Your message',{required:true,rows:5,placeholder:'How can we help?'})}<p class="fine-print">This prepares a text in your messaging app. Press send there to deliver your message.</p><button class="button primary" type="submit">Prepare text ${icon('arrow')}</button><div id="contact-status" role="status"></div></form></section>`;
}
function family() {
  return `${intro('PART OF THE FAMILY', 'All dogs welcome.<br><em>All personalities loved.</em>', 'The faces, muddy paws and little moments that make it all worthwhile.')}<section class="container family-grid section-topless"><div class="family-image">${image('team-dog.webp','A happy moment with a dog and the Barking Mad family','',true)}<div><h2>The best kind of company.</h2><p>Got a favourite photo of your dog? We’d love to see it.</p></div></div><form id="gallery-form" class="form-panel"><p class="eyebrow">SHARE A HAPPY MOMENT</p><h2>Show us your best friend.</h2><div class="form-grid">${field('owner_name','Your name',{autocomplete:'name'})}${field('dog_name','Dog’s name',{required:true})}</div>${field('email','Email (optional)',{type:'email',autocomplete:'email'})}${field('image_url','Photo link (optional)',{type:'url',placeholder:'https://…'})}${field('caption','A little about them (optional)',{rows:3})}<p class="fine-print">We’ll open an email with these details. You can attach a photo in your email app. Submissions aren’t published automatically.</p><button class="button primary" type="submit">Prepare photo email ${icon('arrow')}</button><div id="gallery-status" role="status"></div><a class="text-link" href="/contact/">Need to change or remove a photo? Contact us ${icon('arrow')}</a></form></section>`;
}
function helper() { return `${intro('A LITTLE HELP', 'Good questions.<br><em>Helpful answers.</em>', 'The things people often ask before their first groom or stay.')}<section class="container faq-page section-topless">${faqs(true)}<div class="question-card">${icon('text')}<h2>Got a different question?</h2><p>Tell us what’s on your mind. We’ll reply when we’re free.</p>${link('Text the team', `sms:${B.sms}`)}</div></section>`; }
function profile() { return `${intro('NEXT TIME, A LITTLE EASIER', 'Your saved <em>details.</em>', 'Keep your contact details on this device to fill in your next enquiry.')}<section class="container narrow section-topless"><form id="profile-form" class="form-panel">${field('name','Your name',{autocomplete:'name'})}${field('phone','Phone number',{type:'tel',autocomplete:'tel'})}${field('email','Email (optional)',{type:'email',autocomplete:'email'})}<p class="fine-print">These details are stored only in this browser. There’s no account or sign-in, and nothing is sent to us when you save.</p><div class="actions"><button type="submit" class="button primary">Save details ${icon('check')}</button><button type="button" class="button outline" id="clear-profile">Clear saved details</button></div><div id="profile-status" role="status"></div></form></section>`; }
function admin() { return `${intro('THIS DEVICE ONLY', 'Local enquiry <em>history.</em>', 'Messages prepared in this browser. These records do not confirm a message was sent or an appointment was booked.')}<section class="container section-topless"><div class="notice"><strong>This is not a shared business inbox.</strong><p>Real customer enquiries arrive by text or email. There is no customer login or server database.</p></div><button type="button" class="button outline" id="clear-inbox">Clear history on this device</button><div id="local-inbox" class="local-inbox"></div><p id="inbox-status" role="status"></p></section>`; }
function notFound() { return `${intro('404 / A LITTLE OFF THE LEAD', 'This page has <em>wandered off.</em>', 'Let’s get you and your dog back to the right place.')}<div class="container section-topless actions">${link('Head home', '/')}${link('Find our services', '/services/', 'outline')}</div>`; }
export function renderPage(route) {
  return ({'/':home,'/services/':services,'/boarding/':boarding,'/sanctuary/':sanctuary,'/team/':team,'/our-family/':family,'/helper/':helper,'/contact/':contact,'/book/':book,'/sign-in/':profile,'/admin/':admin,'/404/':notFound}[route] || notFound)();
}
