const AS="/assets/",PHONE="027 247 2493",SMS="+64272472493",EMAIL="barkingmadbarbers@gmail.com";
const STORE="bmb_static_enquiries_v1",PROFILE="bmb_static_profile_v1";
const nav=[["Services","/services"],["Sanctuary","/Sanctuary"],["Our Family","/our-family"],["Team","/team"],["Helper","/helper"],["Contact","/contact"]];
const prices={full:[["Tiny","$80"],["Small","$90"],["Medium","$110"],["Large","$130"]],wash:[["Tiny","$45"],["Small","$50"],["Medium","$55"],["Large","$60"]],extras:[["Flea Shampoo","$20"],["Nail Trim","$20"],["Teeth Brush","$10"],["Face Tidy","$10"],["Anal Gland Expression","$20"]]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const icon=t=>`<span class="icon-sq">${t}</span>`;
const poster=c=>" <div class='"+(c||"poster-card")+"'><img src='"+AS+"hero-advert.png' alt='Barking Mad Barbers advert'></div>";
function setNav(){const h=nav.map(([n,u])=>`<a href="${u}" data-link class="nav-link">${n}</a>`).join("");$(".nav-links").innerHTML=h;$("#mobileDrawer").innerHTML=h+`<a href="/sign-in" data-link class="nav-link">Saved details</a><a href="/book" data-link class="btn btn-gold">Book Now</a>`}
function key(p=location.pathname){p=decodeURIComponent(p).replace(/\/+$/,"").toLowerCase()||"/";return p==="/"? "home":p.includes("family")?"our-family":p.includes("sanctuary")?"sanctuary":p.includes("service")?"services":p.includes("team")?"team":p.includes("book")?"book":p.includes("helper")||p.includes("help")?"helper":p.includes("contact")?"contact":p.includes("sign")||p.includes("login")?"sign-in":p.includes("admin")?"admin":"home"}
function shell(title,kicker,copy,body){return `<div class="wrap page-hero"><div class="page-hero-grid"><div><div class="kicker">${kicker}</div><h1 class="page-title">${title}</h1><p class="lead">${copy}</p></div>${poster("page-poster")}</div></div><div class="wrap">${body}</div>`}
function card(i,t,c){return `<article class="card">${icon(i)}<h3>${t}</h3><p>${c}</p></article>`}
function price(t,from,rows,copy){return `<article class="card price-card"><div class="price-top"><h3>${t}</h3><div class="from">${from}</div></div><div class="price-list"><p>${copy}</p>${rows.map(r=>`<div class="price-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join("")}</div></article>`}
function serviceBlock(){return `<section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Services</div><h2 class="section-title">Clear pricing, beautiful finish.</h2></div><a href="/book" data-link class="btn btn-dark">Book Now</a></div><div class="grid grid-2">${price("Full Groom","from $80",prices.full,"Warm bath, blow dry, brush out, full body clip, face and feet finish, nail trim, ear cleaning and anal gland expression.")}${price("Wash & Dry","from $45",prices.wash,"Warm bath, blow dry, brush out, nail trim, anal gland expression and cologne.")}</div></div></section>`}
function home(){return `<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">Tawa dog grooming</div><h1 class="display">Groomed with <span class="gold">Love.</span><br>Treated like <span class="gold">Family.</span></h1><p class="lead">Premium white, black and gold care with calm appointments, clean finishes and easy booking by text.</p><div class="hero-actions"><a href="/book" data-link class="btn btn-gold">Book Your Dog's Groom</a><a href="/services" data-link class="btn btn-soft">View Services</a></div><div class="lead"><strong>Bookings only - Mon-Sat 8:30-3:00</strong></div></div>${poster()}</div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Why Barking Mad</div><h2 class="section-title">A premium groom without the stress.</h2></div><p class="section-copy">The site runs fully static. Enquiries open as ready-made texts or emails, so there is no server to keep alive.</p></div><div class="grid grid-4">${card("Love","Calm Sanctuary","A peaceful, low-stress space where dogs feel safe and loved.")}${card("Care","Premium Products","Gentle products for a healthy skin and coat finish.")}${card("Pro","Experienced Team","Skilled grooming with patient one-on-one attention.")}${card("Text","Text Bookings","No server needed: booking requests open your text app.")}</div></div></section>${serviceBlock()}${cta()}`}
function services(){return shell('Services & <span class="gold">Prices</span>',"Premium grooming","Choose the service that fits your dog. Final pricing can change if the coat is badly matted or needs extra time.",`<div class="grid grid-2">${price("Full Groom","from $80",prices.full,"Warm bath, shampoo and condition, blow dry, brush out, full body clip, face and feet finish, nail trim, ear cleaning and anal gland expression.")}${price("Wash & Dry","from $45",prices.wash,"Warm bath, shampoo and condition, blow dry, brush out, nail trim, anal gland expression and cologne.")}</div><section class="section"><div class="section-head"><div><div class="kicker">Extras</div><h2 class="section-title">Add-on care.</h2></div></div><div class="grid grid-3">${prices.extras.map(r=>`<article class="clean-card">${icon("Care")}<h3>${r[0]}</h3><p><strong class="gold">${r[1]}</strong> added to your groom when needed.</p></article>`).join("")}</div></section>`)}
function sanctuary(){return shell('Calm <span class="gold">Sanctuary</span>',"Low-stress care","A clean, quiet, appointment-only space made for dogs who need patience, routine and kindness.",`<div class="grid grid-3">${card("Love","Calm first","We work around comfort, coat condition and confidence.")}${card("Paw","One-on-one attention","Less rush, less chaos, more care for each dog.")}${card("Care","Clean products","Gentle grooming products and tidy finish standards.")}</div>`)}
function team(){return shell('Meet the <span class="gold">Team</span>',"Our team","The team page keeps your supplied images and the premium poster style.",`<div class="grid grid-2"><article class="clean-card"><img src="${AS}team-dog.webp" alt="Team member with dog" style="border-radius:24px;aspect-ratio:1/1;object-fit:cover;margin-bottom:18px"><h3>Dog-loving care</h3><p>Friendly, calm and focused on a finish that suits your dog.</p></article><article class="clean-card"><img src="${AS}team-beach.webp" alt="Barking Mad family photo" style="border-radius:24px;aspect-ratio:1/1;object-fit:cover;margin-bottom:18px"><h3>Local Tawa family</h3><p>A Wellington grooming business with a warm, personal feel.</p></article></div>`)}
function family(){return shell('Our <span class="gold">Family</span>',"Loved like our own","Send photo links or family page requests directly by email.",`<div class="split"><form class="card form" id="galleryForm"><h3>Share your dog</h3><div class="form-grid"><div class="field"><label>Your name</label><input name="owner_name"></div><div class="field"><label>Email</label><input name="email" type="email"></div></div><div class="field"><label>Dog name</label><input name="dog_name" required></div><div class="field"><label>Photo URL</label><input name="image_url" placeholder="Paste a photo link"></div><div class="field"><label>Caption</label><textarea name="caption"></textarea></div><button class="btn btn-gold" type="submit">Email Photo Details</button><div id="galleryStatus"></div></form><form class="card form" id="requestForm"><h3>Send a request</h3><div class="form-grid"><div class="field"><label>Your name</label><input name="name" required></div><div class="field"><label>Email</label><input name="email" type="email"></div></div><div class="form-grid"><div class="field"><label>Phone</label><input name="phone"></div><div class="field"><label>Request type</label><input name="request_type"></div></div><div class="field"><label>Message</label><textarea name="message" required></textarea></div><button class="btn btn-dark" type="submit">Text Request</button><div id="requestStatus"></div></form></div>`)}
function serviceOptions(){return["Full Groom","Wash & Dry","Face Tidy","Nail Trim","Teeth Brush","Flea Shampoo"].map(s=>`<label><input type="checkbox" name="services" value="${s}">${s}</label>`).join("")}
function dogEntry(i=1){return `<div class="dog-entry"><div class="dog-entry-head"><div class="dog-entry-title">Dog ${i}</div><button class="btn btn-soft remove-dog" type="button">Remove</button></div><div class="dog-entry-fields"><div class="form-grid"><div class="field"><label>Dog name</label><input name="dog_name" required></div><div class="field"><label>Dog size</label><select name="dog_size" required><option value="">Choose size</option><option>Tiny</option><option>Small</option><option>Medium</option><option>Large</option></select></div></div><div class="form-grid"><div class="field"><label>Breed</label><input name="breed" required></div><div class="field"><label>Preferred time for this dog</label><input name="dog_preferred_time" placeholder="Leave blank for main time"></div></div><div class="field"><label>Services</label><div class="service-stack">${serviceOptions()}</div></div></div></div>`}
function book(){return shell('Book a <span class="gold">Groom</span>',"Bookings only","Send a text booking request. Add each dog with size, breed, services and optional dog-specific times.",`<div class="booking-shell"><form class="booking-form-card form" id="bookingForm"><div class="booking-form-head"><div><h3>Booking request</h3><p>Leave dog-specific times blank when all dogs can use the main preferred time.</p></div><span class="tag goldtag">Text friendly</span></div><div class="booking-form-body"><div class="form-grid"><div class="field"><label>Your name</label><input name="owner_name" required></div><div class="field"><label>Phone</label><input name="phone" required></div></div><div class="form-grid"><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>Preferred date</label><input name="preferred_date" type="date"></div></div><div class="field" id="mainPreferredTimeField"><label>Main preferred time</label><input name="preferred_time" placeholder="Morning / afternoon / exact time"></div><div class="dog-list" id="dogsList">${dogEntry(1)}</div><button class="btn btn-soft add-dog-btn" type="button" id="addDogBtn">+ Add dog</button><div class="field"><label>Notes</label><textarea name="notes"></textarea></div><label class="sms-consent"><input name="booking_sms_consent" type="checkbox" required><span>I understand this enquiry will open as a text message to Barking Mad Barbers.</span></label><button class="btn btn-gold" type="submit">Send Booking Request</button><div id="bookingStatus"></div></div></form><aside class="booking-side"><div class="sms-notice"><h3>Texting works best</h3><p>Booking requests open your text app with the message ready to send.</p><a class="btn btn-dark" id="textToBookBtn" href="sms:${SMS}">Text to Book</a></div><div class="clean-card"><h3>Before you book</h3><div class="note-list"><div class="note"><span class="dot"></span><span>Services can be stacked for each dog.</span></div><div class="note"><span class="dot"></span><span>Breed matters for coat, handling and appointment timing.</span></div><div class="note"><span class="dot"></span><span>Final price depends on size, breed, coat and condition.</span></div></div></div></aside></div>`)}
function helper(){return shell('Grooming <span class="gold">Helper</span>',"Static helper","A quick local guide for common grooming questions. It does not use AI or any server.",`<div class="chat-shell"><div class="chat-phone"><div class="chat-head"><div class="avatar">BM</div><div><div class="chat-name">Barking Mad Helper</div><div class="chat-presence">Local guide - no server</div></div></div><div class="chat-feed" id="chatFeed"><div class="msg-row bot"><div class="avatar">BM</div><div class="bubble">Ask about prices, matting, fleas, hours, or how to book. For anything specific, text ${PHONE}.</div></div></div><form class="chat-composer" id="helperForm"><div class="quick-grid">${["Full groom price","Matted coat","Hours","How to book"].map(t=>`<button type="button" data-ask="${t}">${t}</button>`).join("")}</div><div class="chat-send"><textarea name="question" required placeholder="Message Barking Mad Helper..."></textarea><button class="send-btn" type="submit" aria-label="Send">^</button></div></form></div></div>`)}
function contact(){return shell('Contact <span class="gold">Us</span>',"Tawa, Wellington","Message to book, ask a question or confirm what service your dog needs.",`<div class="grid grid-3">${card("Text","Phone",PHONE)}${card("Book","Hours","Mon-Sat 8:30-3:00")}${card("Paw","Location","5A Tawa Street, Tawa Wellington")}</div><section class="section"><div class="split"><form class="card form" id="contactForm"><h3>Message the team</h3><div class="form-grid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Phone</label><input name="phone"></div></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>Message</label><textarea name="message" required></textarea></div><button class="btn btn-gold" type="submit">Text Message</button><div id="contactStatus"></div></form><div class="clean-card"><h3>Email</h3><p><a href="mailto:${EMAIL}">${EMAIL}</a></p><p>Please text when possible. If a call is easier, send a quick text and the team will call back when they can.</p><div class="hero-actions"><a class="btn btn-gold" href="/book" data-link>Book online</a><a class="btn btn-soft" href="sms:${SMS}">Text now</a></div></div></div></section>`)}
function signIn(){return shell('Saved <span class="gold">Details</span>',"No backend account","Save your name, email and phone on this device only.",`<div class="split"><form class="card form" id="profileForm"><div class="field"><label>Name</label><input name="name"></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>Phone</label><input name="phone"></div><button class="btn btn-gold" type="submit">Save Details</button><div id="signinStatus"></div></form><div class="clean-card" id="profileBox"></div></div>`)}
function admin(){return shell('Static <span class="gold">Enquiries</span>',"No backend dashboard","This page shows enquiries saved on this browser only. Live customer enquiries arrive by text or email.",`<div class="clean-card"><h3>Server removed</h3><p>There is no server login, database, AI log, or shared admin dashboard now. To receive enquiries from customers, use the ready-made SMS and email flows on the public pages.</p><div class="hero-actions"><button class="btn btn-soft" onclick="renderInbox()">Refresh local inbox</button><button class="btn btn-soft" onclick="clearInbox()">Clear local inbox</button></div></div><section class="section"><div id="adminStatus"></div><div id="staticInbox" class="admin-list"></div></section>`)}
function cta(){return `<section class="section"><div class="wrap"><div class="clean-card" style="display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap"><div><div class="kicker">Ready?</div><h2 class="section-title">Make their next groom feel premium.</h2><p class="section-copy">Book a calm appointment at 5A Tawa Street, Tawa Wellington.</p></div><a href="/book" data-link class="btn btn-gold">Message to book</a></div></div></section>`}
function render(){const views={home,services,sanctuary,"our-family":family,team,book,helper,contact,"sign-in":signIn,admin};$("#app").innerHTML=(views[key()]||home)();$$(".nav-link").forEach(a=>a.classList.toggle("active",key(new URL(a.href).pathname)===key()));bindLinks();bindForms();scrollTo(0,0);if(key()==="sign-in")renderProfile();if(key()==="admin")renderInbox()}
function bindLinks(){$$("[data-link]").forEach(a=>a.onclick=e=>{let u=new URL(a.href);if(u.origin===location.origin){e.preventDefault();$("#mobileDrawer").classList.remove("open");if(u.pathname==="/book"){location.href="/book?bmb_v="+Date.now();return}history.pushState({}, "", u.pathname);render()}})}
function toggleMenu(){$("#mobileDrawer").classList.toggle("open")}
addEventListener("popstate",render);
function fd(f){return Object.fromEntries(new FormData(f).entries())}
function dogs(){return $$(".dog-entry").map(e=>{let g=n=>e.querySelector(`[name="${n}"]`)?.value.trim()||"",services=[...e.querySelectorAll('[name="services"]:checked')].map(x=>x.value);return{dog_name:g("dog_name"),dog_size:g("dog_size"),breed:g("breed"),dog_preferred_time:g("dog_preferred_time"),service:services.join(", "),services}})}
function refreshDogs(){$$(".dog-entry").forEach((e,i)=>{e.querySelector(".dog-entry-title").textContent=`Dog ${i+1}`;let r=e.querySelector(".remove-dog");r.classList.toggle("hidden",$$(".dog-entry").length===1);r.onclick=()=>{e.remove();refreshDogs();mainTime()};e.querySelector('[name="dog_preferred_time"]').oninput=mainTime});mainTime()}
function mainTime(){let m=$('#bookingForm [name="preferred_time"]');if(!m)return;let all=dogs().length&&dogs().every(d=>d.dog_preferred_time);m.disabled=all;m.placeholder=all?"Using each dog time below":"Morning / afternoon / exact time";if(all)m.value="";m.closest(".field").classList.toggle("main-time-muted",all)}
function bookingBody(d){let ds=d.dogs||dogs(),pref=(d.preferred_time||"").trim(),date=(d.preferred_date||"").trim(),times=ds.map((x,i)=>`Dog ${i+1} (${x.dog_preferred_time||pref||"use the main preferred time"})`),has=ds.some(x=>x.dog_preferred_time);let appt=has?["Preferred times:",...times,date?`Preferred date ${date}`:""].filter(Boolean).join("\n"):pref&&!/^whenever$/i.test(pref)?`I would like my appointment at ${[pref,date].filter(Boolean).join(" ")}`:`I would like my appointment ${["whenever",date].filter(Boolean).join(" ")}`;let services=ds.flatMap((x,i)=>x.service?[`Dog ${i+1} services: ${x.service}`]:[]);return["Hi Barking Mad Barbers I'd like to enquire about a dog.","",...ds.map((x,i)=>`${i+1} - ${x.dog_name||"Dog"} - ${[x.dog_size,x.breed].filter(Boolean).join(" ")}`),"",...services,"",appt,"",["Cheers",d.owner_name||"",d.phone||""].filter(Boolean).join(" ")].filter((l,i,a)=>l||a[i-1]!== "").join("\n")}
function sms(body){let b=encodeURIComponent(body);return /iPhone|iPad|iPod/i.test(navigator.userAgent)?`sms:${SMS}&body=${b}`:`sms:${SMS}?body=${b}`}
function save(type,data){let a=JSON.parse(localStorage.getItem(STORE)||"[]");a.unshift({id:Date.now().toString(36),type,created_at:new Date().toLocaleString(),data});localStorage.setItem(STORE,JSON.stringify(a.slice(0,100)))}
function fallback(el,body,url,label="Open text message"){el.innerHTML=`<div class="status good sms-open-card"><strong>Your message is ready.</strong><p>If your app does not open, copy this text and send it to ${PHONE}.</p><textarea class="sms-preview" readonly>${esc(body)}</textarea><div class="hero-actions"><button class="btn btn-gold" type="button" id="copyMsg">Copy text</button><a class="btn btn-soft" href="${url}">${label}</a></div></div>`;$("#copyMsg").onclick=async()=>{try{await navigator.clipboard.writeText(body);$("#copyMsg").textContent="Copied"}catch{$("#copyMsg").textContent="Select and copy the text"}}}
function openSms(body,el){let url=sms(body);fallback(el,body,url);if(/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent))location.href=url}
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE)||"null")}catch{return null}}
function bindForms(){let b=$("#bookingForm");if(b){refreshDogs();let p=profile();if(p)["owner_name","email","phone"].forEach(n=>{if(b[n])b[n].value=n==="owner_name"?p.name||"":p[n]||""});let open=()=>{if(!b.reportValidity())return;let first=dogs()[0]||{},data={...fd(b),dogs:dogs(),dog_name:first.dog_name||"",dog_size:first.dog_size||"",breed:first.breed||""},body=bookingBody(data);save("booking",data);openSms(body,$("#bookingStatus"))};$("#addDogBtn").onclick=()=>{$("#dogsList").insertAdjacentHTML("beforeend",dogEntry($$(".dog-entry").length+1));refreshDogs()};$("#textToBookBtn").onclick=e=>{e.preventDefault();open()};b.onsubmit=e=>{e.preventDefault();open()}}let h=$("#helperForm");if(h){$$("[data-ask]").forEach(x=>x.onclick=()=>{h.question.value=x.dataset.ask;h.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}))});h.onsubmit=e=>{e.preventDefault();let q=h.question.value.trim();if(!q)return;append("me",q);h.question.value="";let r=reply(q);append("bot",r);save("helper",{message:q,reply:r})}}let s=$("#profileForm");if(s){let p=profile();if(p){s.name.value=p.name||"";s.email.value=p.email||"";s.phone.value=p.phone||""}s.onsubmit=e=>{e.preventDefault();localStorage.setItem(PROFILE,JSON.stringify(fd(s)));$("#signinStatus").innerHTML='<div class="status good">Saved on this device.</div>';renderProfile()}}let c=$("#contactForm");if(c)c.onsubmit=e=>{e.preventDefault();let d=fd(c),body=[`Name: ${d.name||""}`,`Phone: ${d.phone||""}`,`Email: ${d.email||""}`,"",d.message||""].join("\n");save("contact",d);openSms(body,$("#contactStatus"))};let g=$("#galleryForm");if(g)g.onsubmit=e=>{e.preventDefault();let d=fd(g),body=[`Owner: ${d.owner_name||""}`,`Email: ${d.email||""}`,`Dog: ${d.dog_name||""}`,`Photo URL: ${d.image_url||""}`,"",`Caption: ${d.caption||""}`].join("\n");save("gallery",d);location.href=`mailto:${EMAIL}?subject=${encodeURIComponent("Barking Mad Barbers photo submission")}&body=${encodeURIComponent(body)}`;$("#galleryStatus").innerHTML='<div class="status good">Opening an email with the photo details ready to send.</div>'};let r=$("#requestForm");if(r)r.onsubmit=e=>{e.preventDefault();let d=fd(r),body=[`Request type: ${d.request_type||"Request"}`,`Name: ${d.name||""}`,`Phone: ${d.phone||""}`,`Email: ${d.email||""}`,"",d.message||""].join("\n");save("request",d);openSms(body,$("#requestStatus"))}}
function append(who,text){let f=$("#chatFeed"),row=document.createElement("div");row.className="msg-row "+(who==="me"?"me":"bot");row.innerHTML=who==="me"?`<div class="bubble">${esc(text)}</div>`:`<div class="avatar">BM</div><div class="bubble">${esc(text)}</div>`;f.appendChild(row);f.scrollTop=f.scrollHeight}
function reply(t){let q=t.toLowerCase();if(q.includes("price")||q.includes("cost")||q.includes("full"))return"Full grooms start from $80 tiny, $90 small, $110 medium, and $130 large. Final price depends on coat, breed and condition.";if(q.includes("wash"))return"Wash & Dry starts from $45 tiny, $50 small, $55 medium, and $60 large.";if(q.includes("knot")||q.includes("matt"))return"For knots or matting, book a Full Groom and add notes about the coat condition. Extra charges may apply.";if(q.includes("flea"))return"If fleas are found, flea shampoo is added to the groom as a $20 extra.";if(q.includes("hour")||q.includes("open"))return"Hours are Monday to Saturday, 8:30 to 3:00, bookings only.";if(q.includes("book"))return"Use Book Now and send the prepared text. Texting is best because the team may be with a dog.";return"That is a good one to text through to Barking Mad Barbers. The number is "+PHONE+"."}
function renderProfile(){let p=profile(),box=$("#profileBox");box.innerHTML=p?`<h3>Saved details</h3><p><strong>${esc(p.name||"")}</strong><br>${esc(p.email||"")}<br>${esc(p.phone||"")}</p><button class="btn btn-soft" onclick="localStorage.removeItem(PROFILE);render()">Clear saved details</button>`:"<h3>Your saved details</h3><p>Nothing saved on this browser yet.</p>"}
function renderInbox(){let el=$("#staticInbox");if(!el)return;let a=JSON.parse(localStorage.getItem(STORE)||"[]");$("#adminStatus").innerHTML='<div class="status">Static mode: this only shows messages created on this browser. Customer messages arrive by text or email.</div>';el.innerHTML=a.length?a.map(x=>`<article class="booking-item"><div class="booking-top"><strong>${esc(x.type)}</strong><span class="tag">${esc(x.created_at)}</span></div><pre style="white-space:pre-wrap;font:inherit">${esc(JSON.stringify(x.data,null,2))}</pre></article>`).join(""):'<div class="status">No local enquiries saved on this browser.</div>'}
function clearInbox(){localStorage.removeItem(STORE);renderInbox()}
setNav();render();
