const AS="/assets/",PHONE="027 247 2493",SMS="+64272472493",EMAIL="barkingmadbarbers@gmail.com";
const STORE="bmb_static_enquiries_v1",PROFILE="bmb_static_profile_v1";
const nav=[["Services","/services"],["Boarding","/boarding"]],aboutNav=[["Calm Sanctuary","/Sanctuary"],["Our Family","/our-family"],["Meet the Team","/team"],["Dog Care Helper","/helper"]],navEnd=[["Contact","/contact"]];
const prices={full:[["Tiny","$80"],["Small","$90"],["Medium","$110"],["Large","$130"]],wash:[["Tiny","$45"],["Small","$50"],["Medium","$55"],["Large","$60"]],boarding:[["Overnight stays","by arrangement"],["Comfortable routine","meals, rest and attention"],["Family-style care","treated like one of our own"]],extras:[["Flea Shampoo","$20"],["Nail Trim","$20"],["Teeth Brush","$10"],["Face Tidy","$10"],["Anal Gland Expression","$20"]]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const icon=t=>`<span class="icon-sq">${t}</span>`;
const poster=c=>" <div class='"+(c||"poster-card")+"'><img src='"+AS+"hero-advert.png' alt='Barking Mad Barbers advert'></div>";
const navLink=([n,u])=>`<a href="${u}" data-link class="nav-link">${n}</a>`;
function setNav(){
  $(".nav-links").innerHTML=nav.map(navLink).join("")+
    `<div class="nav-drop"><button class="nav-link drop-btn" type="button" aria-haspopup="true" aria-expanded="false">About<span class="drop-caret">&#9662;</span></button><div class="drop-menu">${aboutNav.map(navLink).join("")}<div class="drop-divider"></div><a href="/sign-in" data-link class="nav-link">Saved details</a></div></div>`+
    navEnd.map(navLink).join("");
  $("#mobileDrawer").innerHTML=[...nav,...navEnd].map(navLink).join("")+
    `<div class="drawer-label">More</div>`+aboutNav.map(navLink).join("")+
    `<a href="/sign-in" data-link class="nav-link">Saved details</a><a href="/book" data-link class="btn btn-gold">Book Now</a>`;
  const drop=$(".nav-drop"),btn=$(".drop-btn");
  btn.onclick=e=>{e.stopPropagation();drop.classList.toggle("open");btn.setAttribute("aria-expanded",drop.classList.contains("open"))};
  document.addEventListener("click",e=>{if(!drop.contains(e.target)){drop.classList.remove("open");btn.setAttribute("aria-expanded","false")}});
  document.addEventListener("keydown",e=>{if(e.key==="Escape"){drop.classList.remove("open");btn.setAttribute("aria-expanded","false")}});
}
function key(p=location.pathname){p=decodeURIComponent(p).replace(/\/+$/,"").toLowerCase()||"/";return p==="/"?"home":p.includes("family")?"our-family":p.includes("board")?"boarding":p.includes("sanctuary")?"sanctuary":p.includes("service")?"services":p.includes("team")?"team":p.includes("book")?"book":p.includes("helper")||p.includes("help")?"helper":p.includes("contact")?"contact":p.includes("sign")||p.includes("login")?"sign-in":p.includes("admin")?"admin":"home"}
function shell(title,kicker,copy,body){return `<div class="wrap page-hero"><div class="page-hero-grid"><div><div class="kicker">${kicker}</div><h1 class="page-title">${title}</h1><p class="lead">${copy}</p></div>${poster("page-poster")}</div></div><div class="wrap">${body}</div>`}
function card(i,t,c){return `<article class="card">${icon(i)}<h3>${t}</h3><p>${c}</p></article>`}
function price(t,from,rows,copy){return `<article class="card price-card"><div class="price-top"><h3>${t}</h3><div class="from">${from}</div></div><div class="price-list"><p>${copy}</p>${rows.map(r=>`<div class="price-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join("")}</div></article>`}
function serviceBlock(){return `<section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Services</div><h2 class="section-title">Grooms, stays and genuine care.</h2></div><a href="/book" data-link class="btn btn-dark">Book Now</a></div><div class="grid grid-3">${price("Full Groom","from $80",prices.full,"Warm bath, blow dry, brush out, full body clip, face and feet finish, nail trim, ear cleaning and anal gland expression.")}${price("Wash & Dry","from $45",prices.wash,"Warm bath, blow dry, brush out, nail trim, anal gland expression and cologne.")}${price("Dog Boarding","ask us",prices.boarding,"Home-style dog boarding for dogs who need a safe place to stay, with comfort, routine and plenty of human attention.")}</div></div></section>`}
function home(){return `<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">Tawa dog grooming & boarding</div><h1 class="display">Groomed with <span class="gold">Love.</span><br>Treated like <span class="gold">Family.</span></h1><p class="lead">We do more than beautiful grooms. We also offer dog boarding where your dog is cared for in a calm, homely setting, with comfort, routine and attention while you are away.</p><div class="hero-actions"><a href="/book" data-link class="btn btn-gold">Book Dog Care</a><a href="/services" data-link class="btn btn-soft">View Services</a></div><div class="lead"><strong>Bookings only - Mon-Sat 8:30-3:00</strong></div></div>${poster()}</div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="kicker">Why Barking Mad</div><h2 class="section-title">A premium groom or stay without the stress.</h2></div><p class="section-copy">Boarding should feel personal: your dog stays somewhere safe, follows their normal routine, gets individual attention and is treated like part of the family.</p></div><div class="grid grid-4">${card("Love","Calm Sanctuary","A peaceful, low-stress space where dogs feel safe and loved.")}${card("Home","Dog Boarding","A homely stay with care, company and routine while you are away.")}${card("Pro","Experienced Team","Skilled grooming with patient one-on-one attention.")}${card("Text","Text Bookings","Booking requests open your text app so enquiries are simple.")}</div></div></section>${serviceBlock()}${cta()}`}
function services(){return shell('Services & <span class="gold">Prices</span>',"Premium grooming & boarding","Choose the service that fits your dog. Grooming prices can change if the coat is badly matted or needs extra time; boarding is arranged by enquiry so we can match your dog's needs.",`<div class="grid grid-3">${price("Full Groom","from $80",prices.full,"Warm bath, shampoo and condition, blow dry, brush out, full body clip, face and feet finish, nail trim, ear cleaning and anal gland expression.")}${price("Wash & Dry","from $45",prices.wash,"Warm bath, shampoo and condition, blow dry, brush out, nail trim, anal gland expression and cologne.")}${price("Dog Boarding","ask us",prices.boarding,"Safe, comfortable boarding that feels less like a kennel and more like staying with people who know and care for dogs.")}</div><section class="section"><div class="section-head"><div><div class="kicker">Extras</div><h2 class="section-title">Add-on care.</h2></div></div><div class="grid grid-3">${prices.extras.map(r=>`<article class="clean-card">${icon("Care")}<h3>${r[0]}</h3><p><strong class="gold">${r[1]}</strong> added to your groom when needed.</p></article>`).join("")}</div></section>`)}
function boarding(){return shell('Dog <span class="gold">Boarding</span>',"Loved like family","When your dog boards with Barking Mad Barbers, the goal is simple: a safe, comfortable stay with familiar routines, real attention and the kind of care you would want from someone looking after your own dog.",`<div class="grid grid-3">${card("Home","A homely stay","Boarding is arranged to feel personal and settled, with comfort, company and calm care.")}${card("Care","Routine matters","Tell us about meals, medication, sleep habits and little quirks so we can keep things familiar.")}${card("Love","Family-style attention","We do not just watch dogs. We get to know them, reassure them and treat them like part of the family.")}</div><section class="section"><div class="clean-card" style="display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap"><div><div class="kicker">Boarding enquiries</div><h2 class="section-title">Tell us about your dog.</h2><p class="section-copy">Send dates, breed, size, temperament, feeding needs and anything that helps us understand the stay.</p></div><a href="/book" data-link class="btn btn-gold">Ask about boarding</a></div></section>`)}
function sanctuary(){return shell('Calm <span class="gold">Sanctuary</span>',"Low-stress care","A clean, quiet, appointment-only space made for dogs who need patience, routine and kindness.",`<div class="grid grid-3">${card("Love","Calm first","We work around comfort, coat condition and confidence.")}${card("Paw","One-on-one attention","Less rush, less chaos, more care for each dog.")}${card("Care","Clean products","Gentle grooming products and tidy finish standards.")}</div>`)}
function team(){return shell('Meet the <span class="gold">Team</span>',"Our team","The team page keeps your supplied images and the premium poster style.",`<div class="grid grid-2"><article class="clean-card"><img src="${AS}team-dog.webp" alt="Team member with dog" style="border-radius:24px;aspect-ratio:1/1;object-fit:cover;margin-bottom:18px"><h3>Dog-loving care</h3><p>Friendly, calm and focused on a finish that suits your dog.</p></article><article class="clean-card"><img src="${AS}team-beach.webp" alt="Barking Mad family photo" style="border-radius:24px;aspect-ratio:1/1;object-fit:cover;margin-bottom:18px"><h3>Local Tawa family</h3><p>A Wellington grooming and boarding business with a warm, personal feel.</p></article></div>`)}
function family(){return shell('Our <span class="gold">Family</span>',"Loved like our own","Send photo links or family page requests directly by email.",`<div class="split"><form class="card form" id="galleryForm"><h3>Share your dog</h3><div class="form-grid"><div class="field"><label>Your name</label><input name="owner_name"></div><div class="field"><label>Email</label><input name="email" type="email"></div></div><div class="field"><label>Dog name</label><input name="dog_name" required></div><div class="field"><label>Photo URL</label><input name="image_url" placeholder="Paste a photo link"></div><div class="field"><label>Caption</label><textarea name="caption"></textarea></div><button class="btn btn-gold" type="submit">Email Photo Details</button><div id="galleryStatus"></div></form><form class="card form" id="requestForm"><h3>Send a request</h3><div class="form-grid"><div class="field"><label>Your name</label><input name="name" required></div><div class="field"><label>Email</label><input name="email" type="email"></div></div><div class="form-grid"><div class="field"><label>Phone</label><input name="phone"></div><div class="field"><label>Request type</label><input name="request_type"></div></div><div class="field"><label>Message</label><textarea name="message" required></textarea></div><button class="btn btn-dark" type="submit">Text Request</button><div id="requestStatus"></div></form></div>`)}
function serviceOptions(){return["Full Groom","Wash & Dry","Face Tidy","Nail Trim","Teeth Brush","Flea Shampoo"].map(s=>`<label><input type="checkbox" name="services" value="${s}">${s}</label>`).join("")}
function dogEntry(i=1){return `<div class="dog-entry"><div class="dog-entry-head"><div class="dog-entry-title">Dog ${i}</div><button class="btn btn-soft remove-dog" type="button">Remove</button></div><div class="dog-entry-fields"><div class="form-grid"><div class="field"><label>Dog name</label><input name="dog_name" required></div><div class="field"><label>Dog size</label><select name="dog_size" required><option value="">Choose size</option><option>Tiny</option><option>Small</option><option>Medium</option><option>Large</option></select></div></div><div class="form-grid"><div class="field"><label>Breed</label><input name="breed" required></div><div class="field"><label>Preferred time for this dog</label><input name="dog_preferred_time" placeholder="Leave blank for main time"></div></div><div class="field"><label>Grooming services</label><div class="service-stack">${serviceOptions()}</div></div></div></div>`}
function boardingFields(){return `<div class="clean-card" id="boardingPanel"><h3>Dog boarding details</h3><div class="form-grid"><div class="field"><label>Dog name</label><input name="boarding_dog_name" required></div><div class="field"><label>Dog breed</label><input name="boarding_breed" required></div></div><div class="form-grid"><div class="field"><label>Dog size</label><select name="boarding_size" required><option value="">Choose size</option><option>Tiny</option><option>Small</option><option>Medium</option><option>Large</option></select></div><div class="field"><label>Estimated meet and greet</label><input name="meet_greet" placeholder="Preferred day or time"></div></div><div class="form-grid"><div class="field"><label>Estimated drop off date</label><input name="drop_off" type="date" required></div><div class="field"><label>Estimated pick up date</label><input name="pick_up" type="date" required></div></div><div class="field"><label>Boarding notes</label><textarea name="boarding_notes" placeholder="Feeding routine, medication, temperament, sleeping habits, or anything we should know."></textarea></div><label class="sms-consent"><input name="boarding_rules_consent" type="checkbox" required><span>I understand that I must bring my own food and Harness & Collar and follow the rules of Pawshake. Peter Reynolds at 5A Tawa St is on Pawshake too.</span></label></div>`}
function book(){return shell('Book Dog <span class="gold">Care</span>',"Grooming & boarding","Tell us what service you need first, then send a text enquiry with the right details ready to go.",`<div class="booking-shell"><form class="booking-form-card form" id="bookingForm"><div class="booking-form-head"><div><h3>Booking request</h3><p>Choose grooming or dog boarding and the form will ask for the right details.</p></div><span class="tag goldtag">Text friendly</span></div><div class="booking-form-body"><div class="form-grid"><div class="field"><label>Your name</label><input name="owner_name" required></div><div class="field"><label>Phone</label><input name="phone" required></div></div><div class="field"><label>What kind of service do you need?</label><select name="service_type" id="serviceType" required><option value="Grooming">Grooming</option><option value="Dog Boarding">Dog Boarding</option></select></div><div class="form-grid"><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field grooming-only"><label>Preferred grooming date</label><input name="preferred_date" type="date"></div></div><div class="field grooming-only" id="mainPreferredTimeField"><label>Main preferred time</label><input name="preferred_time" placeholder="Morning / afternoon / exact time"></div><div id="groomingPanel"><div class="dog-list" id="dogsList">${dogEntry(1)}</div><button class="btn btn-soft add-dog-btn" type="button" id="addDogBtn">+ Add dog</button><div class="field"><label>Grooming notes</label><textarea name="notes"></textarea></div></div>${boardingFields()}<label class="sms-consent"><input name="booking_sms_consent" type="checkbox" required><span>I understand this enquiry will open as a text message to Barking Mad Barbers.</span></label><button class="btn btn-gold" type="submit">Send Enquiry</button><div id="bookingStatus"></div></div></form><aside class="booking-side"><div class="sms-notice"><h3>Texting works best</h3><p>Grooming and boarding enquiries open your text app with the message ready to send.</p><a class="btn btn-dark" id="textToBookBtn" href="sms:${SMS}">Text to Book</a></div><div class="clean-card"><h3>Before you book</h3><div class="note-list"><div class="note"><span class="dot"></span><span>Choose Grooming for the normal grooming form.</span></div><div class="note"><span class="dot"></span><span>Choose Dog Boarding for stay dates, meet and greet, and care notes.</span></div><div class="note"><span class="dot"></span><span>Final grooming price depends on size, breed, coat and condition.</span></div></div></div></aside></div>`)}
function helper(){let body=encodeURIComponent("Hi Barking Mad Barbers, I have a question about my dog.");return shell('Dog Care <span class="gold">Helper</span>',"Text the team","No typing box here. Questions go straight to Barking Mad Barbers by text so nothing gets lost.",`<div class="chat-shell"><div class="chat-phone"><div class="chat-head"><div class="avatar">BM</div><div><div class="chat-name">Barking Mad Helper</div><div class="chat-presence">Text-friendly help</div></div></div><div class="chat-feed" id="chatFeed"><div class="msg-row bot"><div class="avatar">BM</div><div class="bubble">Need help choosing grooming or boarding, asking about matting, pricing, coat condition, stay dates, or booking? Send a text and the team can reply properly when they are free.</div></div></div><div class="chat-composer"><a class="btn btn-gold" style="width:100%" href="sms:${SMS}?body=${body}">Text me with your questions</a><p class="section-copy" style="margin:0">Texting is best because the team may be with a dog and unable to answer a call straight away.</p></div></div></div>`)}
function contact(){return shell('Contact <span class="gold">Us</span>',"Tawa, Wellington","Message to book, ask a question or confirm what service your dog needs.",`<div class="grid grid-3">${card("Text","Phone",PHONE)}${card("Book","Hours","Mon-Sat 8:30-3:00")}${card("Paw","Location","5A Tawa Street, Tawa Wellington")}</div><section class="section"><div class="split"><form class="card form" id="contactForm"><h3>Message the team</h3><div class="form-grid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Phone</label><input name="phone"></div></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>Message</label><textarea name="message" required></textarea></div><button class="btn btn-gold" type="submit">Text Message</button><div id="contactStatus"></div></form><div class="clean-card"><h3>Email</h3><p><a href="mailto:${EMAIL}">${EMAIL}</a></p><p>Please text when possible. If a call is easier, send a quick text and the team will call back when they can.</p><div class="hero-actions"><a class="btn btn-gold" href="/book" data-link>Book online</a><a class="btn btn-soft" href="sms:${SMS}">Text now</a></div></div></div></section>`)}
function signIn(){return shell('Saved <span class="gold">Details</span>',"No backend account","Save your name, email and phone on this device only.",`<div class="split"><form class="card form" id="profileForm"><div class="field"><label>Name</label><input name="name"></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>Phone</label><input name="phone"></div><button class="btn btn-gold" type="submit">Save Details</button><div id="signinStatus"></div></form><div class="clean-card" id="profileBox"></div></div>`)}
function admin(){return shell('Static <span class="gold">Enquiries</span>',"No backend dashboard","This page shows enquiries saved on this browser only. Live customer enquiries arrive by text or email.",`<div class="clean-card"><h3>Server removed</h3><p>There is no server login, database, AI log, or shared admin dashboard now. To receive enquiries from customers, use the ready-made SMS and email flows on the public pages.</p><div class="hero-actions"><button class="btn btn-soft" onclick="renderInbox()">Refresh local inbox</button><button class="btn btn-soft" onclick="clearInbox()">Clear local inbox</button></div></div><section class="section"><div id="adminStatus"></div><div id="staticInbox" class="admin-list"></div></section>`)}
function cta(){return `<section class="section"><div class="wrap"><div class="clean-card" style="display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap"><div><div class="kicker">Ready?</div><h2 class="section-title">Make their next groom or stay feel premium.</h2><p class="section-copy">Book calm care at 5A Tawa Street, Tawa Wellington.</p></div><a href="/book" data-link class="btn btn-gold">Message to book</a></div></div></section>`}
function render(){const views={home,services,boarding,sanctuary,"our-family":family,team,book,helper,contact,"sign-in":signIn,admin};$("#app").innerHTML=(views[key()]||home)();$$("a.nav-link").forEach(a=>a.classList.toggle("active",key(new URL(a.href).pathname)===key()));const db=$(".drop-btn");if(db)db.classList.toggle("active",$$(".drop-menu a.nav-link").some(a=>key(new URL(a.href).pathname)===key()));bindLinks();bindForms();scrollTo(0,0);if(key()==="sign-in")renderProfile();if(key()==="admin")renderInbox()}
function bindLinks(){$$("[data-link]").forEach(a=>a.onclick=e=>{let u=new URL(a.href);if(u.origin===location.origin){e.preventDefault();$("#mobileDrawer").classList.remove("open");$(".nav-drop")?.classList.remove("open");history.pushState({},"",u.pathname);render()}})}
function toggleMenu(){$("#mobileDrawer").classList.toggle("open")}
addEventListener("popstate",render);
function fd(f){return Object.fromEntries(new FormData(f).entries())}
function dogs(){return $$(".dog-entry").map(e=>{let g=n=>e.querySelector(`[name="${n}"]`)?.value.trim()||"",services=[...e.querySelectorAll('[name="services"]:checked')].map(x=>x.value);return{dog_name:g("dog_name"),dog_size:g("dog_size"),breed:g("breed"),dog_preferred_time:g("dog_preferred_time"),service:services.join(", "),services}})}
function refreshDogs(){$$(".dog-entry").forEach((e,i)=>{e.querySelector(".dog-entry-title").textContent=`Dog ${i+1}`;let r=e.querySelector(".remove-dog");r.classList.toggle("hidden",$$(".dog-entry").length===1);r.onclick=()=>{e.remove();refreshDogs();mainTime()};e.querySelector('[name="dog_preferred_time"]').oninput=mainTime});mainTime()}
function mainTime(){let m=$('#bookingForm [name="preferred_time"]');if(!m)return;let all=dogs().length&&dogs().every(d=>d.dog_preferred_time);m.disabled=all;m.placeholder=all?"Using each dog time below":"Morning / afternoon / exact time";if(all)m.value="";m.closest(".field").classList.toggle("main-time-muted",all)}
function toggleServiceFields(){let b=$("#bookingForm"),type=b?.service_type?.value||"Grooming",boarding=type==="Dog Boarding";$("#groomingPanel")?.classList.toggle("hidden",boarding);$("#boardingPanel")?.classList.toggle("hidden",!boarding);$$(".grooming-only").forEach(el=>el.classList.toggle("hidden",boarding));$$("#groomingPanel input,#groomingPanel select,#groomingPanel textarea").forEach(el=>{el.disabled=boarding});$$("#boardingPanel input,#boardingPanel select,#boardingPanel textarea").forEach(el=>{el.disabled=!boarding});mainTime()}
function bookingBody(d){if(d.service_type==="Dog Boarding"){return["Hi Barking Mad Barbers, I'd like to enquire about Dog Boarding.","",`Service needed: ${d.service_type}`,`Dog name: ${d.boarding_dog_name||""}`,`Dog breed: ${d.boarding_breed||""}`,`Dog size: ${d.boarding_size||""}`,`Estimated meet and greet: ${d.meet_greet||""}`,`Estimated drop off: ${d.drop_off||""}`,`Estimated pick up: ${d.pick_up||""}`,"",`Notes: ${d.boarding_notes||""}`,"", "I understand that I must bring my own food and Harness & Collar and follow the rules of Pawshake. Peter Reynolds at 5A Tawa St is on Pawshake too.","",[`Cheers`,d.owner_name||"",d.phone||""].filter(Boolean).join(" ")].filter((l,i,a)=>l||a[i-1]!=="").join("\n")}let ds=d.dogs||dogs(),pref=(d.preferred_time||"").trim(),date=(d.preferred_date||"").trim(),times=ds.map((x,i)=>`Dog ${i+1} (${x.dog_preferred_time||pref||"use the main preferred time"})`),has=ds.some(x=>x.dog_preferred_time);let appt=has?["Preferred times:",...times,date?`Preferred date ${date}`:""].filter(Boolean).join("\n"):pref&&!/^whenever$/i.test(pref)?`I would like my grooming appointment at ${[pref,date].filter(Boolean).join(" ")}`:`I would like my grooming appointment ${["whenever",date].filter(Boolean).join(" ")}`;let services=ds.flatMap((x,i)=>x.service?[`Dog ${i+1} grooming services: ${x.service}`]:[]);return["Hi Barking Mad Barbers, I'd like to enquire about Grooming.","",`Service needed: ${d.service_type||"Grooming"}`,"",...ds.map((x,i)=>`${i+1} - ${x.dog_name||"Dog"} - ${[x.dog_size,x.breed].filter(Boolean).join(" ")}`),"",...services,"",appt,d.notes?`Notes: ${d.notes}`:"","",["Cheers",d.owner_name||"",d.phone||""].filter(Boolean).join(" ")].filter((l,i,a)=>l||a[i-1]!=="").join("\n")}
function sms(body){let b=encodeURIComponent(body);return /iPhone|iPad|iPod/i.test(navigator.userAgent)?`sms:${SMS}&body=${b}`:`sms:${SMS}?body=${b}`}
function save(type,data){let a=JSON.parse(localStorage.getItem(STORE)||"[]");a.unshift({id:Date.now().toString(36),type,created_at:new Date().toLocaleString(),data});localStorage.setItem(STORE,JSON.stringify(a.slice(0,100)))}
function fallback(el,body,url,label="Open text message"){el.innerHTML=`<div class="status good sms-open-card"><strong>Your message is ready.</strong><p>If your app does not open, copy this text and send it to ${PHONE}.</p><textarea class="sms-preview" readonly>${esc(body)}</textarea><div class="hero-actions"><button class="btn btn-gold" type="button" id="copyMsg">Copy text</button><a class="btn btn-soft" href="${url}">${label}</a></div></div>`;$("#copyMsg").onclick=async()=>{try{await navigator.clipboard.writeText(body);$("#copyMsg").textContent="Copied"}catch{$("#copyMsg").textContent="Select and copy the text"}}}
function openSms(body,el){let url=sms(body);fallback(el,body,url);if(/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent))location.href=url}
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE)||"null")}catch{return null}}
function bindForms(){let b=$("#bookingForm");if(b){refreshDogs();toggleServiceFields();let p=profile();if(p)["owner_name","email","phone"].forEach(n=>{if(b[n])b[n].value=n==="owner_name"?p.name||"":p[n]||""});b.service_type.onchange=toggleServiceFields;let open=()=>{toggleServiceFields();if(!b.reportValidity())return;let first=dogs()[0]||{},data={...fd(b),dogs:dogs(),dog_name:first.dog_name||"",dog_size:first.dog_size||"",breed:first.breed||""},body=bookingBody(data);save("booking",data);openSms(body,$("#bookingStatus"))};$("#addDogBtn").onclick=()=>{$("#dogsList").insertAdjacentHTML("beforeend",dogEntry($$(".dog-entry").length+1));refreshDogs();toggleServiceFields()};$("#textToBookBtn").onclick=e=>{e.preventDefault();open()};b.onsubmit=e=>{e.preventDefault();open()}}let s=$("#profileForm");if(s){let p=profile();if(p){s.name.value=p.name||"";s.email.value=p.email||"";s.phone.value=p.phone||""}s.onsubmit=e=>{e.preventDefault();localStorage.setItem(PROFILE,JSON.stringify(fd(s)));$("#signinStatus").innerHTML='<div class="status good">Saved on this device.</div>';renderProfile()}}let c=$("#contactForm");if(c)c.onsubmit=e=>{e.preventDefault();let d=fd(c),body=[`Name: ${d.name||""}`,`Phone: ${d.phone||""}`,`Email: ${d.email||""}`,"",d.message||""].join("\n");save("contact",d);openSms(body,$("#contactStatus"))};let g=$("#galleryForm");if(g)g.onsubmit=e=>{e.preventDefault();let d=fd(g),body=[`Owner: ${d.owner_name||""}`,`Email: ${d.email||""}`,`Dog: ${d.dog_name||""}`,`Photo URL: ${d.image_url||""}`,"",`Caption: ${d.caption||""}`].join("\n");save("gallery",d);location.href=`mailto:${EMAIL}?subject=${encodeURIComponent("Barking Mad Barbers photo submission")}&body=${encodeURIComponent(body)}`;$("#galleryStatus").innerHTML='<div class="status good">Opening an email with the photo details ready to send.</div>'};let r=$("#requestForm");if(r)r.onsubmit=e=>{e.preventDefault();let d=fd(r),body=[`Request type: ${d.request_type||"Request"}`,`Name: ${d.name||""}`,`Phone: ${d.phone||""}`,`Email: ${d.email||""}`,"",d.message||""].join("\n");save("request",d);openSms(body,$("#requestStatus"))}}
function append(who,text){let f=$("#chatFeed"),row=document.createElement("div");row.className="msg-row "+(who==="me"?"me":"bot");row.innerHTML=who==="me"?`<div class="bubble">${esc(text)}</div>`:`<div class="avatar">BM</div><div class="bubble">${esc(text)}</div>`;f.appendChild(row);f.scrollTop=f.scrollHeight}
function reply(t){let q=t.toLowerCase();if(q.includes("board")||q.includes("stay"))return"For dog boarding, use Book Now, choose Dog Boarding, and include dates, meet and greet timing, routine, temperament and care notes.";if(q.includes("price")||q.includes("cost")||q.includes("full"))return"Full grooms start from $80 tiny, $90 small, $110 medium, and $130 large. Final price depends on coat, breed and condition.";if(q.includes("wash"))return"Wash & Dry starts from $45 tiny, $50 small, $55 medium, and $60 large.";if(q.includes("knot")||q.includes("matt"))return"For knots or matting, book a Full Groom and add notes about the coat condition. Extra charges may apply.";if(q.includes("flea"))return"If fleas are found, flea shampoo is added to the groom as a $20 extra.";if(q.includes("hour")||q.includes("open"))return"Hours are Monday to Saturday, 8:30 to 3:00, bookings only.";if(q.includes("book"))return"Use Book Now and send the prepared text. Texting is best because the team may be with a dog.";return"That is a good one to text through to Barking Mad Barbers. The number is "+PHONE+"."}
function renderProfile(){let p=profile(),box=$("#profileBox");box.innerHTML=p?`<h3>Saved details</h3><p><strong>${esc(p.name||"")}</strong><br>${esc(p.email||"")}<br>${esc(p.phone||"")}</p><button class="btn btn-soft" onclick="localStorage.removeItem(PROFILE);render()">Clear saved details</button>`:"<h3>Your saved details</h3><p>Nothing saved on this browser yet.</p>"}
function renderInbox(){let el=$("#staticInbox");if(!el)return;let a=JSON.parse(localStorage.getItem(STORE)||"[]");$("#adminStatus").innerHTML='<div class="status">Static mode: this only shows messages created on this browser. Customer messages arrive by text or email.</div>';el.innerHTML=a.length?a.map(x=>`<article class="booking-item"><div class="booking-top"><strong>${esc(x.type)}</strong><span class="tag">${esc(x.created_at)}</span></div><pre style="white-space:pre-wrap;font:inherit">${esc(JSON.stringify(x.data,null,2))}</pre></article>`).join(""):'<div class="status">No local enquiries saved on this browser.</div>'}
function clearInbox(){localStorage.removeItem(STORE);renderInbox()}
function dotField(){
  if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;
  const c=document.createElement("canvas");c.id="dotField";c.setAttribute("aria-hidden","true");document.body.prepend(c);
  const ctx=c.getContext("2d");let W=0,H=0,dots=[],mx=-9999,my=-9999;
  const REPEL=140,PUSH=2.4,SPRING=.012,FRICTION=.88;
  function seed(){
    W=c.width=innerWidth;H=c.height=innerHeight;
    const n=Math.max(40,Math.min(140,Math.round(W*H/15000)));
    dots=Array.from({length:n},()=>{const hx=Math.random()*W,hy=Math.random()*H;
      return{hx,hy,x:hx,y:hy,vx:0,vy:0,r:1+Math.random()*1.9,a:.2+Math.random()*.45,gold:Math.random()<.72,ph:Math.random()*6.283,sp:.002+Math.random()*.004}});
  }
  seed();addEventListener("resize",seed);
  addEventListener("pointermove",e=>{mx=e.clientX;my=e.clientY});
  addEventListener("pointerdown",e=>{mx=e.clientX;my=e.clientY});
  document.addEventListener("mouseleave",()=>{mx=my=-9999});
  (function tick(t){
    ctx.clearRect(0,0,W,H);
    for(const d of dots){
      const dx=d.x-mx,dy=d.y-my,dist=Math.hypot(dx,dy)||1;
      if(dist<REPEL){const f=(REPEL-dist)/REPEL*PUSH;d.vx+=dx/dist*f;d.vy+=dy/dist*f}
      const wob=Math.sin(t*d.sp+d.ph)*10;
      d.vx+=(d.hx+wob-d.x)*SPRING;d.vy+=(d.hy-wob*.6-d.y)*SPRING;
      d.vx*=FRICTION;d.vy*=FRICTION;d.x+=d.vx;d.y+=d.vy;
      const agitated=Math.min(1,Math.hypot(d.vx,d.vy)/3);
      ctx.beginPath();ctx.arc(d.x,d.y,d.r+agitated*.9,0,6.2832);
      ctx.fillStyle=d.gold?`rgba(183,131,42,${Math.min(.85,d.a+agitated*.4)})`:`rgba(11,10,7,${d.a*.4+agitated*.2})`;
      ctx.fill();
    }
    requestAnimationFrame(tick);
  })(0);
}
setNav();render();dotField();
